--liquibase formatted sql

--changeset alexandr:001-initial-schema

CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    is_deleted    BOOLEAN   DEFAULT FALSE                 NOT NULL,
    version       BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE UNIQUE INDEX idx_users_email_uniq_active
    ON users (email)
    WHERE is_deleted = false;

CREATE TABLE roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    version BIGINT DEFAULT 0                        NOT NULL,

    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uc_roles_name UNIQUE (name)
);

CREATE TABLE users_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES roles (role_id)
);

CREATE TABLE users_info
(
    user_id     BIGINT           NOT NULL,
    last_name   VARCHAR(255)     NOT NULL,
    first_name  VARCHAR(255)     NOT NULL,
    middle_name VARCHAR(255),
    version     BIGINT DEFAULT 0 NOT NULL,

    CONSTRAINT pk_users_info PRIMARY KEY (user_id),
    CONSTRAINT fk_users_info_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE participants
(
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by     BIGINT                                  NOT NULL,
    last_name      VARCHAR(255)                            NOT NULL,
    first_name     VARCHAR(255)                            NOT NULL,
    middle_name    VARCHAR(255),
    bio            TEXT,
    telegram       VARCHAR(255),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    version        BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_participants PRIMARY KEY (participant_id),
    CONSTRAINT fk_participants_created_by FOREIGN KEY (created_by) REFERENCES users_info (user_id)
);

CREATE TABLE semesters
(
    semester_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT                                    NOT NULL,
    starts_at   TIMESTAMP                               NOT NULL,
    ends_at     TIMESTAMP                               NOT NULL,
    version     BIGINT DEFAULT 0                        NOT NULL,

    CONSTRAINT pk_semesters PRIMARY KEY (semester_id),
    CONSTRAINT uc_semesters_name UNIQUE (name)
);

CREATE TABLE project_status
(
    project_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              TEXT,
    version           BIGINT DEFAULT 0                        NOT NULL,

    CONSTRAINT pk_project_status PRIMARY KEY (project_status_id),
    CONSTRAINT uc_project_status_name UNIQUE (name)
);

CREATE TABLE projects
(
    project_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by        BIGINT                                  NOT NULL,
    project_status_id BIGINT                                  NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    description       TEXT,
    tech_stack        VARCHAR(255),
    team_size         INTEGER,
    version           BIGINT DEFAULT 0                        NOT NULL,

    CONSTRAINT pk_projects PRIMARY KEY (project_id),
    CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users_info (user_id),
    CONSTRAINT fk_projects_status FOREIGN KEY (project_status_id) REFERENCES project_status (project_status_id)
);

CREATE TABLE project_status_history
(
    project_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id                BIGINT                                  NOT NULL,
    from_status_id            BIGINT                                  NOT NULL,
    to_status_id              BIGINT                                  NOT NULL,
    changed_by                BIGINT                                  NOT NULL,
    changed_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    version                   BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_project_status_history PRIMARY KEY (project_status_history_id),
    CONSTRAINT fk_psh_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_psh_from_status FOREIGN KEY (from_status_id) REFERENCES project_status (project_status_id),
    CONSTRAINT fk_psh_to_status FOREIGN KEY (to_status_id) REFERENCES project_status (project_status_id),
    CONSTRAINT fk_psh_changed_by FOREIGN KEY (changed_by) REFERENCES users_info (user_id)
);

CREATE TABLE project_revisions
(
    project_revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT                                  NOT NULL,
    created_by          BIGINT                                  NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    description         TEXT,
    note                TEXT,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    version             BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_project_revisions PRIMARY KEY (project_revision_id),
    CONSTRAINT fk_pr_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_pr_created_by FOREIGN KEY (created_by) REFERENCES users_info (user_id)
);

CREATE TABLE project_comments
(
    project_comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id         BIGINT                                  NOT NULL,
    author_id          BIGINT                                  NOT NULL,
    body               TEXT                                    NOT NULL,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    version            BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_project_comments PRIMARY KEY (project_comment_id),
    CONSTRAINT fk_pc_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_pc_author FOREIGN KEY (author_id) REFERENCES users_info (user_id)
);

CREATE TABLE project_votes
(
    project_vote_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id      BIGINT                                  NOT NULL,
    voter_id        BIGINT                                  NOT NULL,
    value           BOOLEAN                                 NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    version         BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_project_votes PRIMARY KEY (project_vote_id),
    CONSTRAINT uc_project_votes_unique UNIQUE (project_id, voter_id),
    CONSTRAINT fk_pv_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_pv_voter FOREIGN KEY (voter_id) REFERENCES users_info (user_id)
);

CREATE TABLE teams
(
    team_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    version     BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_teams PRIMARY KEY (team_id),
    CONSTRAINT fk_teams_created_by FOREIGN KEY (created_by) REFERENCES users_info (user_id)
);

CREATE TABLE team_membership
(
    team_membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_id            BIGINT                                  NOT NULL,
    participant_id     BIGINT                                  NOT NULL,
    role               VARCHAR(255),
    joined_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    left_at            TIMESTAMP,
    version            BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_team_membership PRIMARY KEY (team_membership_id),
    CONSTRAINT fk_tm_team FOREIGN KEY (team_id) REFERENCES teams (team_id),
    CONSTRAINT fk_tm_participant FOREIGN KEY (participant_id) REFERENCES participants (participant_id)
);

CREATE TABLE project_teams
(
    project_team_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id      BIGINT                                  NOT NULL,
    team_id         BIGINT                                  NOT NULL,
    semester_id     BIGINT                                  NOT NULL,
    active          BOOLEAN                                 NOT NULL,
    assigned_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    unassigned_at   TIMESTAMP,
    version         BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_project_teams PRIMARY KEY (project_team_id),
    CONSTRAINT uc_project_teams_unique UNIQUE (project_id, team_id, semester_id),
    CONSTRAINT fk_pt_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_pt_team FOREIGN KEY (team_id) REFERENCES teams (team_id),
    CONSTRAINT fk_pt_semester FOREIGN KEY (semester_id) REFERENCES semesters (semester_id)
);

CREATE TABLE team_meetings
(
    team_meeting_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_id         BIGINT                                  NOT NULL,
    created_by      BIGINT                                  NOT NULL,
    scheduled_at    TIMESTAMP                               NOT NULL,
    location        TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    version         BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_team_meetings PRIMARY KEY (team_meeting_id),
    CONSTRAINT fk_tmt_team FOREIGN KEY (team_id) REFERENCES teams (team_id),
    CONSTRAINT fk_tmt_created_by FOREIGN KEY (created_by) REFERENCES users_info (user_id)
);

CREATE TABLE meeting_tasks
(
    meeting_task_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_meeting_id BIGINT                                  NOT NULL,
    title           TEXT                                    NOT NULL,
    description     TEXT                                    NOT NULL,
    due_at          TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP,
    version         BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_meeting_tasks PRIMARY KEY (meeting_task_id),
    CONSTRAINT fk_mt_meeting FOREIGN KEY (team_meeting_id) REFERENCES team_meetings (team_meeting_id)
);

CREATE TABLE project_milestones
(
    project_milestone_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_team_id      BIGINT                                  NOT NULL,
    created_by           BIGINT                                  NOT NULL,
    title                VARCHAR(255)                            NOT NULL,
    description          TEXT,
    due_at               TIMESTAMP,
    version              BIGINT DEFAULT 0                        NOT NULL,

    CONSTRAINT pk_project_milestones PRIMARY KEY (project_milestone_id),
    CONSTRAINT fk_pm_project_team FOREIGN KEY (project_team_id) REFERENCES project_teams (project_team_id),
    CONSTRAINT fk_pm_created_by FOREIGN KEY (created_by) REFERENCES users_info (user_id)
);

CREATE TABLE milestone_evaluations
(
    milestone_evaluation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_milestone_id    BIGINT                                  NOT NULL,
    evaluator_type          VARCHAR(255)                            NOT NULL,
    evaluator_user_id       BIGINT                                  NOT NULL,
    external_contact        TEXT                                    NOT NULL,
    score                   NUMERIC                                 NOT NULL,
    feedback                TEXT,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    version                 BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_milestone_evaluations PRIMARY KEY (milestone_evaluation_id),
    CONSTRAINT fk_me_milestone FOREIGN KEY (project_milestone_id) REFERENCES project_milestones (project_milestone_id),
    CONSTRAINT fk_me_evaluator FOREIGN KEY (evaluator_user_id) REFERENCES users_info (user_id),
    CONSTRAINT chk_evaluator_type CHECK (evaluator_type IN ('external', 'mentor'))
);


