--liquibase formatted sql

--changeset alexandr:001-initial-schema

CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    is_deleted    BOOLEAN   DEFAULT FALSE                 NOT NULL,
    version       BIGINT    DEFAULT 0                     NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE UNIQUE INDEX idx_users_email_uniq_active
    ON users (email)
    WHERE is_deleted = false;

CREATE TABLE roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    version BIGINT DEFAULT 0                        NOT NULL,

    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uc_roles_name UNIQUE (name)
);

CREATE TABLE users_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES roles (role_id)
);

CREATE TABLE users_info
(
    user_id     BIGINT           NOT NULL,
    last_name   VARCHAR(255)     NOT NULL,
    first_name  VARCHAR(255)     NOT NULL,
    middle_name VARCHAR(255),
    version     BIGINT DEFAULT 0 NOT NULL,

    CONSTRAINT pk_users_info PRIMARY KEY (user_id),
    CONSTRAINT fk_users_info_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
